CREATE TABLE PATIENT(
Fname VARCHAR(15) NOT NULL,
Mname VARCHAR(15),
Lname VARCHAR(15) NOT NULL,
Ssn CHAR(9) PRIMARY KEY,
Phone CHAR(10),
Address VARCHAR(60),
Email VARCHAR(25),
DOB DATE NOT NULL,
Insurance_provider VARCHAR(20),
Provider_Ssn CHAR(9) REFERENCES PROVIDER(Ssn));

CREATE TABLE PROVIDER(
Fname VARCHAR(15) NOT NULL,
Mname VARCHAR(15),
Lname VARCHAR(15) NOT NULL,
Title VARCHAR(5) NOT NULL,
Ssn CHAR(9) PRIMARY KEY,
Phone CHAR(10),
Email VARCHAR(25),
Salary INT NOT NULL);

CREATE TABLE MEDICATION(
Brand_name VARCHAR(20) PRIMARY KEY,
Chemical_name VARCHAR(30) UNIQUE,
Classification VARCHAR(20));

CREATE TABLE HEALTH_CONDITION(
Condition_name VARCHAR(25) PRIMARY KEY,
Condition_type VARCHAR(15));

CREATE TABLE APPOINTMENT(
Reason_for_visit VARCHAR(60),
Appt_time TIME,
Appt_date DATE,
Copayment INT,
Provider_Ssn CHAR(9) REFERENCES PROVIDER(Ssn),
Patient_Ssn CHAR(9) REFERENCES PATIENT(Ssn),
PRIMARY KEY (Appt_time, Appt_date, Provider_Ssn),
UNIQUE (Appt_time, Appt_date, Patient_Ssn));

CREATE TABLE PRESCRIPTION(
Brand_name VARCHAR(20) REFERENCES MEDICATION(Brand_name),
Patient_Ssn CHAR(9) REFERENCES PATIENT(Ssn),
Dosage VARCHAR(10) NOT NULL,
DATE_PRESCRIBED DATE,
PRIMARY KEY (Brand_name, Patient_Ssn));

CREATE TABLE DIAGNOSIS(
Condition_name VARCHAR(25) REFERENCES HEALTH_CONDITION(Condition_name),
Patient_Ssn CHAR(9) REFERENCES PATIENT(Ssn),
Date_diagnosed DATE,
PRIMARY KEY (Condition_name, Patient_Ssn));

CREATE TABLE DO_NOT_MIX(
Brand_name1 VARCHAR(20) NOT NULL REFERENCES MEDICATION(Brand_name),
Brand_name2 VARCHAR(20) NOT NULL REFERENCES MEDICATION(Brand_name));

CREATE TABLE TREATMENT_FOR(
Brand_name VARCHAR(20) NOT NULL REFERENCES MEDICATION(Brand_name),
Condition_name VARCHAR(25) NOT NULL REFERENCES HEALTH_CONDITION(Condition_name));

CREATE TABLE SYMPTOMS (
Condition_name VARCHAR(25) NOT NULL REFERENCES HEALTH_CONDITION(Condition_name),
Symptom VARCHAR(20) NOT NULL);

CREATE TABLE SIDE_EFFECTS(
Brand_name VARCHAR(20) NOT NULL REFERENCES MEDICATION(Brand_name),
Side_effect VARCHAR(20) NOT NULL);










