LOAD DATA LOCAL INFILE './patient.csv'
INTO TABLE PATIENT
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 0 ROWS;

LOAD DATA LOCAL INFILE './provider.csv'
INTO TABLE PROVIDER
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 0 ROWS;

LOAD DATA LOCAL INFILE './medication.csv'
INTO TABLE MEDICATION
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 0 ROWS;

LOAD DATA LOCAL INFILE './health_condition.csv'
INTO TABLE HEALTH_CONDITION
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 0 ROWS;

LOAD DATA LOCAL INFILE './appointment.csv'
INTO TABLE APPOINTMENT
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 0 ROWS;

LOAD DATA LOCAL INFILE './prescription.csv'
INTO TABLE PRESCRIPTION
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 0 ROWS;

LOAD DATA LOCAL INFILE './diagnosis.csv'
INTO TABLE DIAGNOSIS
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 0 ROWS;

LOAD DATA LOCAL INFILE './do_not_mix.csv'
INTO TABLE DO_NOT_MIX
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 0 ROWS;

LOAD DATA LOCAL INFILE './treatment_for.csv'
INTO TABLE TREATMENT_FOR
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 0 ROWS;

LOAD DATA LOCAL INFILE './symptoms.csv'
INTO TABLE SYMPTOMS
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 0 ROWS;

LOAD DATA LOCAL INFILE './side_effects.csv'
INTO TABLE SIDE_EFFECTS
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 0 ROWS;
